window:
  padding:
    x: 3
    y: 3

font:
  normal:
    family: Roboto Mono
    style: Regular
  bold:
    family: Roboto Mono
    style: Bold
  italic:
    family: Roboto Mono
    style: Italic
  size: 12

key_bindings:
  - { key: Equals,         mods: Control, action: None }
  - { key: Plus,           mods: Control, action: None }
  # - { key: NumpadAdd,      mods: Control, action: IncreaseFontSize }
  - { key: Minus,          mods: Control, action: None } 
  # - { key: NumpadSubtract, mods: Control, action: DecreaseFontSize }
