[[repos]]
url = "localhost"
name = "LOCAL"
definitions_version = 1

[[repos.themes]]
name = "custom"
directory = "/home/elgusanito/.config/leftwm/themes/custom"
version = "0.0.0"
leftwm_versions = "*"
current = true
